declare const _default: {
	s: {
		oneSecond: number;
		fiveSeconds: number;
		tenSeconds: number;
		halfMinute: number;
		oneMinute: number;
		fiveMinutes: number;
		tenMinutes: number;
		thirtyMinutes: number;
		oneHour: number;
		twoHours: number;
		threeHours: number;
		fourHours: number;
		fiveHours: number;
		sixHours: number;
		oneDay: number;
		twoDays: number;
		sevenDays: number;
		thirtyDays: number;
		sixMonths: number;
	};
	ms: {
		oneSecond: number;
		fiveSeconds: number;
		tenSeconds: number;
		halfMinute: number;
		oneMinute: number;
		fiveMinutes: number;
		tenMinutes: number;
		thirtyMinutes: number;
		oneHour: number;
		twoHours: number;
		threeHours: number;
		fourHours: number;
		fiveHours: number;
		sixHours: number;
		oneDay: number;
		twoDays: number;
		sevenDays: number;
		thirtyDays: number;
		sixMonths: number;
	};
};
export default _default;
